[project]
name = "backend"
version = "0.1.0"
description = "Backend for clackclub"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.127.0",
    "openai>=2.14.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.45",
]

[dependency-groups]
dev = ["ruff>=0.14.10"]

[tool.uv]
package = true

[tool.ruff]
exclude = ["alembic/**"]

[tool.ruff.lint]
extend-select = ["I"]
